### ISSUE TITLE
how do I get the slack token?

### ISSUE THREAD

**Issue by giuliomoro** [manelizzard/flarum-notify#3]
The instructions on the slack website seem to be oriented at the app developers more than the app's user.
https://api.slack.com/web
https://api.slack.com/docs/oauth

**Comment by manelizzard** [comment]
You can get your tokens here: https://api.slack.com/tokens

**Comment by giuliomoro** [comment]
Would you mind to elaborate?
At that address I get this:

"My Authorizations
You haven't authorized any Slack applications."

<img width="1207" alt="screen shot 2017-03-19 at 20 35 23" src="https://cloud.githubusercontent.com/assets/4260604/24084517/a1c0a16e-0ce3-11e7-9398-8451f0a9428e.png">

Do I need to install a slack app first? What's the name of the app? "flarum" gives no results if I search in here https://instrumentslab.slack.com/apps .
Thanks

**Comment by giuliomoro** [comment]
Just to elaborate on my request, the `flarum-notify` extension says in the dialog in the admin panel:
"In order to obtain the token, visit https://api.slack.com/web"
I then go to that page and it says:

"Authentication
Authenticate your Web API requests by providing a bearer token, which identifies a single user.
Register your application with Slack to obtain credentials for use with our OAuth 2.0 implementation, which allows you to negotiate tokens on behalf of users and teams. Tokens should be passed in all Web API calls as a parameter called token."

A step-by-step guide on how to obtain the Slack token for use in `flarum-notify` would be greatly appreciated.

**Comment by manelizzard** [comment]
How to obtain the Slack token is properly described, step by step, on theirs website. Please read carefully their documentation.
